# Generated by Django 3.2.9 on 2021-11-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211116_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerprofilesocialnetwork',
            options={'verbose_name': 'Seller_Profile_Social_Network', 'verbose_name_plural': 'Seller_Profiles_Social_Networks'},
        ),
    ]
